version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: "dev"
  ignore:
  - dependency-name: com.opencsv:opencsv
    versions:
    - "5.3"
    - "5.4"

