language: java
jdk:
  - oraclejdk8
sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - ./gradlew downloadDependencies
after_script:
  - ./gradlew sendCoverageToCodacy

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
    - build/libs/RADAR-Commons-0.1.jar
    - build/libs/RADAR-Commons-0.1-javadoc.jar
    - build/libs/RADAR-Commons-0.1-sources.jar
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - ./gradlew bintrayUpload