language: java
jdk:
  - oraclejdk8
sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/3.*.*
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - ./gradlew downloadDependencies
after_script:
  - ./gradlew sendCoverageToCodacy

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file_glob: true
    file:
      - "build/libs/*.jar"
      - "testing/build/libs/*.jar"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew artifactoryPublish --info --stacktrace
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      tags: true
